### PR TITLE
replace cljs.reader/reader-error with js/Error as function was remove…

### PR DESCRIPTION
**Pull request by va511e**
…d in clojurescript 1.9.854 commit 07ee2250af02b25f232111890c0f40f23150768d

### CODE REVIEW

**Comment by cemerick** [comment]
The tests pass fine for me locally FWIW. The travis error is pretty weird (`ERROR: TTY could not be found.`!); didn't make much headway in looking into that for 10m. Maybe there's an easy fix from someone that knows their unix better than I. If not, there are other ways to kill the browser process after completion that might be feasible.

Anyway, would like to see this merged. I have the privs to do so, but don't want to step on any toes. Right now, cljs-priority-map (and thus other projects, like loom) can't be used with the latest CLJS.

**Comment by cemerick** [comment]
Oh, dammit, I pushed here instead of to my own fork. 

I've now forced master back to where it was. ☹️

**Comment by den1k** [comment]
Have Travis been rerun? Is the error related to this commit?

**Comment by den1k** [comment]
All tests on this build pass ✅️

```
➜  cljs-priority-map git:(master) lein cljsbuild test phantomjs
Compiling ClojureScript...
Compiling "public/test.js" from ["test"]...
Successfully compiled "public/test.js" in 10.744 seconds.
Running ClojureScript test: phantomjs
"Elapsed time: 145.523931 msecs"


"Elapsed time: 76.665541 msecs"


"Elapsed time: 80.158367 msecs"


"Elapsed time: 64.482502 msecs"


"Elapsed time: 71.320093 msecs"


"Elapsed time: 75.709451 msecs"


"Elapsed time: 79.088716 msecs"


"Elapsed time: 100.356665 msecs"


"Elapsed time: 64.776548 msecs"


"Elapsed time: 103.007471 msecs"


"Elapsed time: 87.797793 msecs"


"Elapsed time: 94.760860 msecs"


"Elapsed time: 85.206905 msecs"


"Elapsed time: 105.006480 msecs"


"Elapsed time: 199.795032 msecs"


"Elapsed time: 103.220680 msecs"


"Elapsed time: 82.688778 msecs"


"Elapsed time: 135.250442 msecs"


"Elapsed time: 130.871947 msecs"


"Elapsed time: 134.363038 msecs"


Done.
```

**Comment by cemerick** [comment]
@den1k Yeah, it tests fine for me, too. The failures are due exclusively to travis issues with xvfb IIRC.

I've been relying upon my own forked build in the meantime…

**Comment by den1k** [comment]
@cemerick well, if the bug is in travis that shouldn't hold back the merge.

**Comment by cemerick** [comment]
I would agree, but that's not my call to make.

**Comment by den1k** [comment]
@alandipert?

**Comment by alandipert** [comment]
Thanks @cemerick and @den1k. I'll release shortly.

**Pull request merged**
